services:

  backend:
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_USER=process.env.POSTGRES_USER
      - POSTGRES_PASSWORD=process.env.POSTGRES_USER
    volumes: 
      - postgres:/var/lib/postgesql/data
    ports: 
      - '5432:5432'


  volumes:
    postgres:
